steps:
  - label: "pre wait"
    command: "echo This step occurred before a wait"
  - wait
  - label: "post wait"
    command: "echo This step occurred after a wait"
  - label: "pre block"
    command: "echo This step occurred before a block"
  - block: "block"
  - label: "post block"
    command: "echo This step occurred after a block"
